### ISSUE TITLE
ESM transition TODO

### ISSUE THREAD

**Issue by talentlessguy** [tinyhttp/tinyhttp#235]
In tinyhttp 2 ( https://github.com/talentlessguy/tinyhttp/milestone/2) there will be no CommonJS builds. Most modules are hand-written so it can't all be transitioned at once. This issue is to keep track of the progress.

# 3rd-party modules

- [x] `es-mime-types` ([PR](https://github.com/talentlessguy/es-mime-types/pull/1))
- [x] `es-fresh` ([PR](https://github.com/talentlessguy/es-fresh/pull/1))
- [x] `es-vary` ([PR](https://github.com/talentlessguy/es-vary/pull/1))
- [x] `es-content-type`

## wares

- [x] bot-detector
- [x] jwt
- [x] cookie-parser
- [x] logger
- [x] cors
- [x] dotenv
- [ ] ip-filter
- [x] rate-limit
- [x] unless

more coming soon

**Comment by talentlessguy** [comment]
WIP on https://github.com/talentlessguy/tinyhttp/tree/esm
