### ISSUE TITLE
Tests TODO

### ISSUE THREAD

**Issue by talentlessguy** [tinyhttp/tinyhttp#92]
The final goal is of this issue is to achieve ~80-100% coverage

here's a todo list of things that require tests (based on the `__tests__`  folder):

> :warning: List is in progress, I'll be adding new test tasks over time, here are some that you can submit already

- [ ] core
   - [ ] app
     - [x] `app` - `app.set`, `app.enable`, `app.disable` ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/app/src/app.ts#L96))
     - [x] `onError` - Test a case where an error doesn't have an HTTP status code, neither is a string ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/app/src/onError.ts#L14))
   - [ ] request
   - [ ] response
- [ ] modules
   - [x] accepts
   - [x] cookie-signature
   - [x] cookie
   - [x] etag (#133)
   - [x] req (#140)
   - [x] res
      - [x] `res.format` - if `default` only is specified, call it as a function ([codecov]())
      - [x] `res.format` - if nothing is specified, throw 406 ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/res/src/format.ts#L28))
   - [ ] router
   - [x] send (#143)
- [x] wares
   - [x] cookie-parser
   - [x] cors
     - [x] Accept a function to set origin
   - [x] dotenv
   - [x] favicon
   - [x] jwt
     - [x] Should work with different algorithms ([codecov](https://codecov.io/gh/talentlessguy/tinyhttp/src/master/packages/jwt/src/index.ts#L30)) [pending]
   - [x] logger
   - [x] ping
   - [x] bot-detector (#111) 
   - [x] ip-filter
   - [x] jsonp (#123)\

If you want to help with tests, write down to this thread with your questions

**Comment by talentlessguy** [comment]
Thanks for improved coverage for `accepts` by @BRA1L0R via #97

**Comment by aneeshrelan** [comment]
Can I try adding tests for bot-detector?

**Comment by talentlessguy** [comment]
@aneeshrelan yup, will create a separate issue for that now

**Comment by talentlessguy** [comment]
@aneeshrelan check https://github.com/talentlessguy/tinyhttp/issues/111

**Comment by aneeshrelan** [comment]
@talentlessguy I see some tests for the mentioned wares, are they still needed?

**Comment by shubhi23994** [comment]
I can take up some tests

**Comment by talentlessguy** [comment]
@shubhi23994 which tests would you like to take up? I will create a separate issue for those u picked

**Comment by talentlessguy** [comment]
@aneeshrelan I receive lots of PRs during hacktoberfest so I could have missed some of them

and yes, tests are still needed

**Comment by shubhi23994** [comment]
I can pick up jsonp to start with

**Comment by talentlessguy** [comment]
@shubhi23994 alright, making a new issue then :D

**Comment by talentlessguy** [comment]
@shubhi23994 write in #123 so i can assign you

**Comment by MaurizioPz** [comment]
Hi, may I take pick ETag?

**Comment by talentlessguy** [comment]
@MaurizioPz yup, pls wait a sec imma setting up a new issue for this (to later assign it to you)

**Comment by talentlessguy** [comment]
@MaurizioPz check this: #133

**Comment by MaurizioPz** [comment]
Hi, may I take also req

**Comment by talentlessguy** [comment]
@MaurizioPz alright, making a new issue

**Comment by talentlessguy** [comment]
@MaurizioPz check #140 and write there pls so I can assign you

**Comment by alcar** [comment]
Hey, @talentlessguy! I'm not familiar with the codebase, but I'm happy to try writing some tests if you still need it!

**Comment by talentlessguy** [comment]
@alcar hi! you can pick any of the things to test, and I'll open a separate issue for you - e.g. if you decide to test `@tinyhttp/session` - I'll create an issue "Write tests for @tinyhttp/session"

pick the one you want and I'll assign you to those tests

**Comment by alcar** [comment]
Do you have any recommendations for a newcomer? If not, I can just pick up the first available from the list!

**Comment by talentlessguy** [comment]
@alcar `@tinyhttp/send` is quite easy to test, so i'd pick that

but feel free to pick anything else

**Comment by alcar** [comment]
@talentlessguy Sounds great! Could you please create an issue and assign it to me then?

**Comment by talentlessguy** [comment]
@alcar yup currently making an issue for you

**Comment by talentlessguy** [comment]
@alcar here you go -> #143

**Comment by alcar** [comment]
@talentlessguy I'm happy to pick up a new one if you still need it!

**Comment by talentlessguy** [comment]
@alcar i will setup an issue for testing `@tinyhttp/session` for you tomorrow

**Comment by KoljaTM** [comment]
Would like to help out as well. Anything up for grabs?

**Comment by talentlessguy** [comment]
@alcar  check this => https://github.com/talentlessguy/tinyhttp/issues/163

**Comment by talentlessguy** [comment]
@KoljaTM `@tinyhttp/pug` has 0% coverage so you can take it

or other modules with almost 100% coverage, such as `@tinyhttp/cors`

**Comment by KoljaTM** [comment]
ok, i'll see what i can do for the pug package

**Comment by MVelez94** [comment]
I'm interested in contributing tests. I think `wares/favicon` would be small enough and beginner friendly. How do I start?

**Comment by Khotam** [comment]
hi @talentlessguy, i would like to contribute but have no experience with open source projects. could you give me some easier tasks?

**Comment by ismail5701** [comment]
Hey, I would like to help with `wares/cookie-parser` . Could you please create a subtask for the same?

**Comment by talentlessguy** [comment]
@ismailmmd no need to, just submit the PR and link to this issue (write like `related to #92`)

**Comment by talentlessguy** [comment]
@Khotam take a look at other tasks

**Comment by ismailmmd** [comment]
@talentlessguy I think the above list is not updated. I checked and saw `favicon` and `cookie-parser` repos have 💯  `>99%` coverage

**Comment by talentlessguy** [comment]
@ismailmmd cookie parser has an uncovered line with secret array I think, would you like to write a test for it? or just make sure it's covered

**Comment by ismailmmd** [comment]
@talentlessguy will give it a try 👍

**Comment by ismailmmd** [comment]
Created a PR for `cookie-parser` @talentlessguy 🙏 please review

**Comment by talentlessguy** [comment]
@ismailmmd merged!

**Comment by ismailmmd** [comment]
@talentlessguy  Added one more PR to `jwt`

**Comment by hoseinprd** [comment]
Hi there.
how can I participate?

**Comment by talentlessguy** [comment]
@hoseinprd would be nice to cover this part of code on router: https://coveralls.io/builds/55425079/source?filename=packages%2Frouter%2Fsrc%2Findex.ts#L134

**Comment by hoseinprd** [comment]
ok bro

**Comment by talentlessguy** [comment]
I think this can be closed because code coverage is nearly 100%
